#  Parametry sterownika
IP = '192.168.0.1'
RACK = 0
SLOT = 1

# Paramtery Serwera
port = 1024
IP_serv ='localhost'

# Parametry Baz Danych
LOCALDMCCONTROLLERPARAM = 103
SAMPLES_DB = 100
GLOBALDATA_DB = 102
ADAPTIVE_PARAM_DB = 101
Valve_oppening_degree_ADDRESS = 0
START_ADDRESS = 0
ke_ADDRESS = 2
Flow_ADDRESS = 4
Power_of_heater_ADDRESS = 8
Thout_ADDRESS = 12
T_ADDRESS = 30
Thout_zad_ADDRESSS = 44
Ku_ADDRESS = 44
JUMP_ADDRESS = 58
TP_ADDRESS = 66
ST_HOLD_ADDRESS = 82
SCENARIUSZ = 83
TC_LOCAL_ADDRESS = 0
ke_LOCAL_ADDRESS = 4
KU_LOCAL_ADDRESS = 8
TC_ADAPTIVE_ADDRESS = 1668
ke_ADAPTIVE_ADDRESS = 1676
KU_ADAPTIVE_ADDRESS = 1680

## Bity podanych zmiennych
STEROWANIE_CHMURA = 5
SET_POINT_CHANGE = 2

# Rozmiary zmiennych
REAL_SIZE = 4
INT_SIZE = 2
BOOL_SIZE = 1

